import '../model/gas_station.dart';
import '../model/gasoline.dart';

// final fakeGasStation = [
//   GasStation(
//       id: '1',
//       brand: "TotalEnergies",
//       name: "Total Relais Valenciennes",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "1.951"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "1.991"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2.000"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,760"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "5 Avenue de l'Europe",
//       zipCode: "59300",
//       city: "Valenciennes",
//       latitude: "50.36910360074033",
//       longitude: "3.531535184659247"),
//   GasStation(
//       id: '2',
//       brand: "Auchan",
//       name: "Auchan petite foret",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "2,101"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "2,067"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2,066"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,749"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "125 Rue Jean Jaurès",
//       zipCode: "59494",
//       city: "Petite Foret",
//       latitude: "50.377024202849576",
//       longitude: "3.474960536901897"),
//   GasStation(
//       id: '3',
//       brand: "Shell",
//       name: "Shell Express",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "2,101"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "2,067"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2,009"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,749"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "91 Rue de Valenciennes",
//       zipCode: "59300",
//       city: "Valenciennes",
//       latitude: "50.40387019381914",
//       longitude: "3.676084117686998"),
//   GasStation(
//       id: "4",
//       brand: "Esso",
//       name: "Esso Express Valenciennes",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "2,101"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "2,067"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2,009"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,749"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "3 boulevard Eisen",
//       zipCode: "59300",
//       city: "Valenciennes",
//       latitude: "50.363660872587374",
//       longitude: "3.5301876715698257"),
//   GasStation(
//       id: "5",
//       brand: "Tx Express",
//       name: "Tx express erquelinnes",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "2,101"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "2,067"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2,009"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,749"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "240 Route de Mons ",
//       zipCode: "65600",
//       city: "erquelinnes",
//       latitude: "50.31252195382443",
//       longitude: "4.135637415748128"),
//   GasStation(
//       id: "6",
//       brand: "E.Leclerc",
//       name: "E.Leclerc Valenciennes",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "2,101"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "2,067"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2,009"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,749"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "1 Rue de la bleue du Nord",
//       zipCode: "59300",
//       city: "Valenciennes",
//       latitude: "50.3735175238767",
//       longitude: "3.540997031172526"),
//   GasStation(
//       id: "7",
//       brand: "Intermarché",
//       name: "Intermarché Express",
//       gasolineList: [
//         Gasoline(
//             id: '1',
//             gasStationId: "",
//             name: "Sans Plomb 98 (E5)",
//             code: "268-661",
//             price: "2,101"),
//         Gasoline(
//             id: '2',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E5)",
//             code: "181-869",
//             price: "2,067"),
//         Gasoline(
//             id: '3',
//             gasStationId: "",
//             name: "Sans Plomb 95 (E10)",
//             code: "067-502",
//             price: "2,009"),
//         Gasoline(
//             id: "4",
//             gasStationId: "",
//             name: "Superéthanol E85",
//             code: "974-006",
//             price: "0,749"),
//         Gasoline(
//             id: "5",
//             gasStationId: "",
//             name: "Gazole (B7)",
//             code: "699-991",
//             price: "2,059"),
//         Gasoline(
//             id: "6",
//             gasStationId: "",
//             name: "GPL",
//             code: "379-503",
//             price: "0,749"),
//       ],
//       lane: "940 Avenue Jean Jaurès",
//       zipCode: "59174",
//       city: "La sentinelle",
//       latitude: "50.34587157883379",
//       longitude: "3.4772542850616817"),
// ];
